name: Advanced Biometric Fraud Prevention CI/CD Pipeline

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/biometric-fraud-system:latest
  ML_MODEL_REGISTRY: mlflow://localhost:5000

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: backend
            path: backend/
          - component: frontend
            path: frontend/
          - component: ml-models
            path: ml-models/
          - component: services
            path: services/
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # For git history in semantic versioning
    
    - name: Setup Node.js
      if: matrix.component == 'frontend' || matrix.component == 'services'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Setup Python
      if: matrix.component == 'backend' || matrix.component == 'ml-models'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies (Node)
      if: matrix.component == 'frontend' || matrix.component == 'services'
      run: |
        cd ${{ matrix.path }}
        npm ci --frozen-lockfile
    
    - name: Install dependencies (Python)
      if: matrix.component == 'backend' || matrix.component == 'ml-models'
      run: |
        cd ${{ matrix.path }}
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run linters
      run: |
        if [ "${{ matrix.component }}" = "backend" ] || [ "${{ matrix.component }}" = "ml-models" ]; then
          cd ${{ matrix.path }}
          flake8 .
          black --check .
          mypy .
        else
          cd ${{ matrix.path }}
          npm run lint
        fi
    
    - name: Run unit tests
      run: |
        if [ "${{ matrix.component }}" = "backend" ] || [ "${{ matrix.component }}" = "ml-models" ]; then
          cd ${{ matrix.path }}
          pytest tests/ -v --cov=. --cov-report=xml --junitxml=test-results.xml
          coverage report -m
        else
          cd ${{ matrix.path }}
          npm test -- --coverage --watchAll=false
        fi
    
    - name: Run integration tests
      if: matrix.component == 'services' || matrix.component == 'backend'
      run: |
        cd ${{ matrix.path }}
        docker-compose -f docker-compose.test.yml up --abort-on-container-exit
        docker-compose -f docker-compose.test.yml down
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.component }}
        path: |
          test-results.xml
          coverage.xml
          coverage/

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run SAST with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/r2c-ci
        generate_sarif: true
    
    - name: Run SCA with Dependabot
      uses: github/dependabot-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker security scan
      uses: azure/container-scan@v1
      with:
        image-source: docker-compose.yml  # Scan all images in compose
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
    
    - name: Secret scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --no-verification

  build-and-package:
    runs-on: ubuntu-latest
    needs: [lint-and-test, security-scan]
    strategy:
      matrix:
        service: [api-gateway, biometric-service, fraud-detection, ml-service, transaction-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/${{ matrix.service }}
        file: ./services/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}-${{ matrix.service }}:latest, ${{ env.DOCKER_IMAGE }}-${{ matrix.service }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build ML models package
      if: matrix.service == 'ml-service'
      run: |
        cd ml-models/
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* --skip-existing
    
    - name: Package frontend
      if: matrix.service == 'frontend'
      run: |
        cd frontend/
        npm run build
        tar -czf frontend-build.tar.gz -C dist .
        # Upload artifact for deployment

  ml-model-training:
    runs-on: ubuntu-latest
    needs: build-and-package
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup ML environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install ML dependencies
      run: |
        pip install -r ml/requirements.txt
        pip install mlflow torch transformers scikit-learn pandas numpy
    
    - name: Download training data
      run: |
        # Simulate data download (use secure storage)
        mkdir -p ml/data/raw
        echo "synthetic,biometric,data,for,training" > ml/data/raw/training_sample.csv
        # In production: aws s3 sync s3://bucket/training-data/ ml/data/raw/
    
    - name: Train fraud detection models
      env:
        MLFLOW_TRACKING_URI: ${{ env.ML_MODEL_REGISTRY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd ml/
        python scripts/train_pipeline.py --model-type ensemble --data-path data/raw/ --epochs 50
        python scripts/train_pipeline.py --model-type transformer --data-path data/raw/ --epochs 30
        python scripts/train_pipeline.py --model-type adversarial --data-path data/raw/ --epochs 40
    
    - name: Log model metrics to MLflow
      run: |
        cd ml/
        mlflow models build-docker -m "models:/ensemble_fraud_detector/Production" -n ensemble-docker
    
    - name: Validate model performance
      run: |
        cd ml-models/
        python -m pytest tests/ -v --runslow --tb=short
    
    - name: Register trained models
      run: |
        mlflow models register -m "runs:/<run_id>/ensemble" -n production_ensemble_fraud_detector
        # Replace <run_id> with actual from training

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-and-package, ml-model-training]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to staging K8s
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          infrastructure/kubernetes/*.yaml
        images: |
          ${{ env.DOCKER_IMAGE }}-api-gateway:latest
          ${{ env.DOCKER_IMAGE }}-biometric-service:latest
          ${{ env.DOCKER_IMAGE }}-fraud-detection:latest
        namespace: staging
        kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}
        strategy: blue-green  # Zero-downtime rollout
    
    - name: Update ML models in staging
      run: |
        kubectl rollout restart deployment/ml-service -n staging
        kubectl wait --for=condition=Available deployment/ml-service -n staging --timeout=300s
    
    - name: Run smoke tests
      run: |
        # Health checks
        curl -f https://staging.example.com/health || exit 1
        curl -f https://staging.example.com/api/biometric/verify || exit 1
    
    - name: Notify Slack on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: '🚀 Staging deployment successful for ${{ github.ref }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment: 
      name: production
      url: https://prod.example.com
      deployment-branch: main  # Protection rule
    
    steps:
    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: owner, maintainer
        minimum-approvals: 1
        issue-title: 'Production deployment approval needed'
    
    - name: Deploy to production K8s
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          infrastructure/kubernetes/*.yaml
        images: |
          ${{ env.DOCKER_IMAGE }}-api-gateway:${{ github.sha }}
          ${{ env.DOCKER_IMAGE }}-biometric-service:${{ github.sha }}
          ${{ env.DOCKER_IMAGE }}-fraud-detection:${{ github.sha }}
        namespace: production
        kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}
        strategy: blue-green
        traffic-split: 90-10  # Gradual rollout
    
    - name: Promote ML models to production
      run: |
        mlflow models stage -m "models:/production_ensemble_fraud_detector" -s Production
        kubectl rollout restart deployment/ml-service -n production
        kubectl wait --for=condition=Available deployment/ml-service -n production --timeout=600s
    
    - name: Run comprehensive tests
      run: |
        # Load testing with Locust
        docker run -v $(pwd)/load-tests:/mnt locustio/locust -f /mnt/locustfile.py --headless -u 100 -r 10 --run-time 5m --host=https://prod.example.com
        # Security validation
        npx owasp-zap-cli start --self-contained
        npx owasp-zap-cli spider https://prod.example.com --spider-self-contained
        npx owasp-zap-cli active-scan https://prod.example.com
    
    - name: Monitor post-deployment
      run: |
        # Prometheus queries for 5min
        for i in {1..5}; do
          curl -s "http://prometheus:9090/api/v1/query?query=up" | jq .
          sleep 60
        done
        # Alert if any service down
        if ! curl -f https://prod.example.com/health; then
          echo "Health check failed!"
          exit 1
        fi
    
    - name: Notify on production deploy
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        fields: repo,message,author,action,eventName,ref,workflow
        text: '🎉 Production deployment successful! Blue-green rollout completed.'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    
    - name: Rollback on failure
      if: failure()
      run: |
        kubectl rollout undo deployment/api-gateway -n production
        kubectl rollout undo deployment/biometric-service -n production
        echo "Rollback initiated due to failure"

  semantic-release:
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js for release
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: https://registry.npmjs.org/
    
    - name: Semantic Release
      run: |
        npm ci
        npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    # Additional stages for robustness
    # ... (extend with canary releases, A/B testing, etc.)

# Global workflow permissions
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  checks: write
  deployments: write
